name: build-develop

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_call:


jobs:
  build_against_dev_release:
    name: build_against_dev
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:    
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache

    - name: Checkout pkg
      uses: actions/checkout@main
      with:
        repository: ${{ github.repository }}
        path: scratch/${{ github.repository }}

    - name: run build in docker container
      run: |
      
        cd $GITHUB_WORKSPACE/scratch
        cat << EOT > build_pkg.sh
        #!/bin/bash
        
        cd /opt/artdaq
        source /opt/artdaq/setupARTDAQDEMO
        
        spack cd --env
        for pkg in */;do 
            echo "Updating package \$pkg"
            cd \$pkg
            git stash
            git checkout develop
            git stash pop
            git pull
            cd ..
        done
        cd /opt/artdaq

        export REPO=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
        cp -pr /scratch/art-daq/$REPO srcs

        echo "Starting build"
        spack install
        res=\$?
        
        echo "Spack install completed with status code \$res"
        echo "Spack install completed with status code \$res" >>/scratch/art-daq/build.log

        exit \$?
        EOT
        chmod +x build_pkg.sh

        docker run --rm -v $GITHUB_WORKSPACE/scratch:/scratch eflumerf/artdaq-spack:latest /scratch/build_pkg.sh
    
    - name: Check build log for success
      run: |
        grep "Spack install completed with status code 0" ${{ github.workspace }}/scratch/art-daq/build.log
    