name: build-develop

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches-ignore: 
      - develop
      - stable
    paths-ignore:
      - 'docs/**'
      - '.github/**'
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: "0 7 * * *"

  workflow_dispatch:
  workflow_call:

jobs:
  build_against_dev_release:
    name: build_against_dev
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@main

    - name: change dir permission
      run: |
        sudo chmod -R go+rwx /var/lib/cvmfs

    - name: Cache cvmfs cache
      id: cvmfs_cache
      uses: actions/cache@main
      with:
        path: /var/lib/cvmfs/shared
        key: cachecvmfs

    - name: restore dir permission
      run: |
        sudo chown -R cvmfs.cvmfs /var/lib/cvmfs
        sudo chmod -R go-rwx /var/lib/cvmfs
    
    - name: Checkout pkg
      uses: actions/checkout@main
      with:
        repository: ${{ github.repository }}
        path: scratch/${{ github.repository }}

    - name: run build in docker container with cvmfs bind mount
      run: |
      
        cd $GITHUB_WORKSPACE/scratch
        cat << EOT > build_pkg.sh
        #!/bin/bash
        
        cd /opt/artdaq
        source /opt/artdaq/setupARTDAQDEMO || exit 1
        
        echo "Checking out develop"
        spack cd --env
        for pkg in */;do 
            echo "Updating package \$pkg"
            cd \$pkg
            git stash
            git checkout develop
            git stash pop
            git pull
            cd ..
        done
        cd /opt/artdaq

        export REPO=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
        echo "Copying /scratch/art-daq/\$REPO to environment ${REPO//_/-}"
        spack cd --env
        cp -pr /scratch/art-daq/\$REPO ${REPO//_/-}

        echo "Starting build"
        spack install 2>&1 | tee /scratch/art-daq/build.log
        
        exit \$?
        EOT
        chmod +x build_pkg.sh

        docker run --rm -v /cvmfs:/cvmfs:shared -v $GITHUB_WORKSPACE/scratch:/scratch eflumerf/artdaq-spack:latest /scratch/build_pkg.sh
        
    - name: upload build log file
      uses: actions/upload-artifact@main
      with:
        name: build_log
        path: ${{ github.workspace }}/scratch/art-daq/build.log

    - name: change dir permission again
      run: |
        sudo chmod -R go+rwx /var/lib/cvmfs