name: Test Single Pkg Workflow (otsdaq version)

on:
  workflow_call:

jobs:

  build_single_pkg:
    name: build single pkg
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache

    - uses: cvmfs-contrib/github-action-cvmfs@main

    - name: change dir permission
      run: |
        sudo chmod -R go+rwx /var/lib/cvmfs

    - name: Cache cvmfs cache
      id: cvmfs_cache
      uses: actions/cache@main
      with:
        path: /var/lib/cvmfs/shared
        key: cachecvmfs

    - name: restore dir permission
      run: |
        sudo chown -R cvmfs.cvmfs /var/lib/cvmfs
        sudo chmod -R go-rwx /var/lib/cvmfs
    
    - name: Checkout pkg
      uses: actions/checkout@main
      with:
        repository: ${{ github.repository }}
        path: scratch/${{ github.repository }}

    - name: run build in docker container with cvmfs bind mount
      run: |
      
        cd $GITHUB_WORKSPACE/scratch
        cat << EOT > build_pkg.sh
        #!/bin/bash
        
        cd /opt/artdaq
        source /opt/artdaq/setup_ots.sh || exit 1
        
        export REPO=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
        echo "Copying /scratch/art-daq/\$REPO to environment \${REPO//_/-}"
        spack cd --env
        if [ -d \${REPO//_/-} ];then rm -rf \${REPO//_/-}; fi
        cp -pr /scratch/art-daq/\$REPO \${REPO//_/-}
        
        spack install
        spack cd -b \${REPO//_/-}
        spack build-env \${REPO//_/-} make && make test | tee /scratch/art-daq/build.log
        res=\$?

        exit \$res
        EOT
        chmod +x build_pkg.sh

        docker run --rm -v /cvmfs:/cvmfs:shared -v $GITHUB_WORKSPACE/scratch:/scratch eflumerf/otsdaq-spack:latest /scratch/build_pkg.sh
        
    - name: Check build log for success
      run: |
        grep "100% tests passed, 0 tests failed" ${{ github.workspace }}/scratch/art-daq/build.log

    - name: upload build log file
      uses: actions/upload-artifact@main
      with:
        name: build_log
        path: ${{ github.workspace }}/scratch/art-daq/build.log

    - name: change dir permission again
      run: |
        sudo chmod -R go+rwx /var/lib/cvmfs